### ISSUE TITLE
Errors shown on RefResolutionError are unclear

### ISSUE THREAD

**Issue by dudicoco** [sirosen/check-jsonschema#22]
When referencing a specific remote schema within a local schema file the validator fails.

This only seems to happen on the https://json.schemastore.org/prometheus.rules.json schema.

To recreate:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "prometheusRules": {
      "$ref": "https://json.schemastore.org/prometheus.rules.json"
    }
  }
}
```

values.yaml:
```yaml
prometheusRules:
  groups:
  - name: test
    rules:
    - alert: test
      expr: |
        absent(up{release="test"} == 1)
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: test
```

```sh
$ pre-commit run check-jsonschema -a
Validate values.....................................................Failed
- hook id: check-jsonschema
- exit code: 1

Traceback (most recent call last):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 774, in resolve_from_url
    document = self.store[url]
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_utils.py", line 22, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: 'https://json.schemastore.org/prometheus.rules'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 777, in resolve_from_url
    document = self.resolve_remote(url)
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 863, in resolve_remote
    with urlopen(uri) as url:
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/bin/check-jsonschema", line 8, in <module>
    sys.exit(main())
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/check_jsonschema/__init__.py", line 14, in main
    checker.run()
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/check_jsonschema/checker.py", line 51, in run
    validator.validate(instance=doc)
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 352, in validate
    for error in self.iter_errors(*args, **kwargs):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 282, in properties
    for error in validator.descend(
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 263, in ref
    for error in validator.descend(instance, resolved):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 282, in properties
    for error in validator.descend(
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 81, in items
    for error in validator.descend(item, items, path=index):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 282, in properties
    for error in validator.descend(
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 81, in items
    for error in validator.descend(item, items, path=index):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 337, in oneOf
    errs = list(validator.descend(instance, subschema, schema_path=index))
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 259, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 766, in resolve
    return url, self._remote_cache(url)
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 779, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: HTTP Error 404: Not Found
```

**Comment by sirosen** [comment]
Thanks for the info; this lets me see the same error.
I also confirmed that this is an issue specific to the schemastore prometheus schema. I was able to create a scenario analogous to yours in which a ref to a known-valid schemastore schema (the github workflows one) works correctly.

I'm 99% certain at this point that it's just the fact that the prometheus schema has a bad `$id` field.
I'll use this scenario to work on improving the error reporting in `check-jsonschema` and then file an upstream issue.

**Comment by sirosen** [comment]
I've just pushed a commit to `main` which makes the error in this case clearer, as it traverses and prints some of the most relevant info from chained exceptions on ref resolution errors.

Example output:
```
$ check-jsonschema --schemafile schema.json values.yaml
Failure resolving $ref within schema

RefResolutionError: HTTP Error 404: Not Found
  in "/home/sirosen/projects/check-jsonschema/src/check_jsonschema/checker.py", line 99
  >>> errors = self._build_error_map(validator, instances)

  caused by

  HTTPError: HTTP Error 404: Not Found
    in "/home/sirosen/projects/check-jsonschema/.venv/lib/python3.8/site-packages/jsonschema/validators.py", line 777
    >>> document = self.resolve_remote(url)

    caused by

    KeyError: 'https://json.schemastore.org/prometheus.rules'
      in "/home/sirosen/projects/check-jsonschema/.venv/lib/python3.8/site-packages/jsonschema/validators.py", line 774
      >>> document = self.store[url]
```

I also confirmed that the sample content passes the prometheus schema if it is corrected to have an accurate `$id`.

I'm retitling the issue, as there is no relevant bug in `check-jsonschema` or the underlying `jsonschema` library.

**Comment by sirosen** [comment]
I've opened an issue upstream, https://github.com/SchemaStore/schemastore/issues/1928

With that and improved error handling in place within `check-jsonschema`, there's nothing more to be done here. I'm closing; tracking can continue on the upstream issue.

**Comment by dudicoco** [comment]
Thanks @sirosen!
